services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "${MONGO_DB_PORT}:27017"
    volumes:
      - mongo:/data/db
    networks:
      - microservices
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15-alpine
    container_name: postgresql_db
    ports:
      - "${POSTGRESQL_DB_PORT}:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - microservices
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRESQL_DB_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL_DB_PASSWORD}
      - POSTGRES_DB=${PRODUCT_DB_NAME}
      - PGDATA=/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRESQL_DB_USERNAME} -d ${PRODUCT_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  config-server:
    build:
      # context: Indica la ruta base desde donde se leerán los archivos (el directorio actual)
      context: .
      # dockerfile: Especifica el nombre del archivo que contiene las instrucciones de construcción
      dockerfile: ./config-server/Dockerfile

    container_name: config-server
    ports:
      - "${CONFIG_SERVER_PORT}:8888"
    networks:
      - microservices
    healthcheck:
      # indico que mi microservicio esta disponible cuando el endpoint /actuator/health me devuelva un status 200
      test: [ "CMD", "curl", "-f", "http://config-server:8888/actuator/health" ]
      interval: 20s
      timeout: 3s
      retries: 5
    restart: on-failure

  discovery-server:
    build:
      context: .
      dockerfile: ./discovery-server/Dockerfile
    container_name: discovery-server
    ports:
      - "${EUREKA_SERVER_PORT}:8761"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
    networks:
      - microservices
    depends_on:
      # este y los demás, deben esperar a que el config server esté listo
      config-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://discovery-server:8761/actuator/health" ]
      interval: 20s
      timeout: 3s
      retries: 5
    restart: on-failure

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "${API_GATEWAY_PORT}:8222"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    networks:
      - microservices
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    restart: on-failure

  customer-microservice:
    build:
      context: .
      dockerfile: ./microservices/customer-microservice/Dockerfile
    container_name: customer-microservice
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      mongodb:
        condition: service_started
    ports:
      - "${CUSTOMER_MICROSERVICE_PORT}:8091"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_MONGODB_URI=mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongodb:27017/${CUSTOMER_DB_NAME}?authSource=admin
    networks:
      - microservices

  product-microservice:
    build:
      context: .
      dockerfile: ./microservices/product-microservice/Dockerfile
    container_name: product-microservice
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      postgres:
        condition: service_started
    ports:
      - "${PRODUCT_MICROSERVICE_PORT}:8092"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${PRODUCT_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${POSTGRESQL_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRESQL_DB_PASSWORD}
    networks:
      - microservices

  cart-microservice:
    build:
      context: .
      dockerfile: ./microservices/cart-microservice/Dockerfile
    container_name: cart-microservice
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      mongodb:
        condition: service_started
    ports:
      - "${CART_MICROSERVICE_PORT}:8098"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_MONGODB_URI=mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongodb:27017/${CART_DB_NAME}?authSource=admin
    networks:
      - microservices

volumes:
  mongo:
  postgres:

networks:
  microservices:
    driver: bridge
