spring:
    application:
        name: config-server
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/config

server:
    port: 8888

# Habilitamos el gestor de salud de Spring Actuator
management:
    endpoints:
        web:
            exposure:
                # permite acceder a las rutas /actuator/* desde la web
                include: health, info, prometheus
    endpoint:
        health:
            show-details: always
