spring:
  mongodb:
    host: localhost
    port: 27017
    database: customer_db
    username: admin
    password: password
    authentication-database: admin


logging:
  level:
    root: INFO
    com.vicma.microservices: WARN
  pattern:
    # formato con hilo, nivel, logger (nombre del logger con max 36 caracteres)
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n' 
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/customer-microservice.log
    max-size: 10MB
    max-files: 30
    

server:
  port: 8091
