spring:
  mongodb:
      uri: mongodb://localhost:27017/customer_db

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO
    com.vicma.microservices: WARN
  pattern:
    # formato con hilo, nivel, logger (nombre del logger con max 36 caracteres)
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n' 
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/customer-microservice.log
    max-size: 10MB
    max-files: 30
    

server:
  port: 8091
