server:
  port: 8761

eureka: 
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
    endpoint:
      health:
        show-details: always
