spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: root
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    root: INFO
    com.vicma.microservices: WARN
  pattern:
    # Formato con hilo, nivel, logger (máximo 36 caracteres)
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr([%thread]){faint} %clr(%-5level) %clr(%logger{36}){cyan} %clr(-){faint} %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

  file:
    name: logs/product-microservice.log
    max-size: 10MB
    max-files: 30

server:
  port: 8092